export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited ...',
  description: 'Get access to our exclusive app ..',
  buttonLabel: 'Button1',
  imgStart: false,
  img: 'svg-1',
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headline: 'Unlimited ...',
  description: 'Get access to our exclusive app ..',
  buttonLabel: 'Button1',
  imgStart: true,
  img: 'svg-1',
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headline: 'Unlimited ...',
  description: 'Get access to our exclusive app ..',
  buttonLabel: 'Button1',
  imgStart: false,
  img: 'svg-1',
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};
